apiVersion: v1
kind: Service
metadata:
    name: "saikube-3737"
    labels:
        app: "saikube-3737"
spec:
    type: LoadBalancer
    ports:
    - port: 443
      targetPort: 443
      protocol: TCP
      name: http
    selector:
        app: "saikube-3737"